lune-climate/ts-results-es

jest.config.js
src/index.ts
src/option.ts
src/result.ts
src/rxjs-operators/index.ts
test/err.test.ts
test/ok.test.ts
test/option.test.ts
test/result.test.ts
test/rxjs.test.ts
test/util.ts

These imports are needed for the ESM version of the library to be
actually importable.

Include .js extensions in internal imports explicitly

---

package-cjs.json
package-esm.json
package.json
src/package.json
src/rxjs-operators/package.json
tsconfig-cjs.json
tsconfig-esm.json

In [1] I made the package ESM-only to make it possible to import
it easily from Lune's ESM code. This is not great so I found a way
to restore the CommonJS compatibility while still resolving the
ESM-related issues[2] found in the original ts-results package.
The solution I found can be found in [3].
[1] 0be48c527e86 ("Make the package ESM-only")
[2] https://github.com/vultix/ts-results/issues/37
[3] https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html

Restore CommonJS compatibility

---

src/result.ts
test/err.test.ts

This is useful to get access to the "underlying" error in global
exception-handling code for example.
Feature requested in [1] and I had a question about something similar as
well[2].
[1] https://github.com/vultix/ts-results/issues/34
[2] https://github.com/vultix/ts-results/issues/48
This change depends on #17 and #19 to be merged first (then the branch will be updated to contain these changes and the build will succeed).

Include error cause in unwrap()/expect() errors

---

README.md

This is a port of https://github.com/vultix/ts-results/pull/46
to the ts-results-es fork.
The original description by Drew De Ponte (@drewdeponte):
That way users are aware of its existance without having to dig through
code and can understand a crucial component of being able to change
functions that return Results with other results.

Add andThen documentation

---

README.md
src/result.ts
test/err.test.ts
test/ok.test.ts

This is a port of https://github.com/vultix/ts-results/pull/45
to the ts-results-es fork, original author: TheDudeFromCI.
This is a feature useful for testing (where one *expects* an error
in some cases and wants an exception thrown otherwise).

Add the Result.expectErr() method

---

README.md
src/option.ts
src/result.ts
test/err.test.ts
test/ok.test.ts
test/option.test.ts

This is a useful composition mechanism when we want to both provide a
default value or map an existing value in the same operation.

Implement mapOr()

---

README.md

I forgot to put it there when I added mapOr().

Add a missing readme index link for mapOr()/mapOrElse()

---

README.md
src/result.ts
test/err.test.ts
test/ok.test.ts

It's one of the functions that's been missing from the API and
we wanted to use it a few times already when we check for errors
in tests.
Closes GH-27.

Implement Result.unwrapErr()

---

src/option.ts
src/result.ts

See the docstrings for details, basically if it's statically safe to use val it should be used because it's obvious there's a value there and there won't be an exception (unwrap()/except() are conditional and may throw, val isn't).

Nudge unwrap()/except() users towards val

---

package-lock.json
package.json

We currently have two package.json files which I want to remove but first let's make sure that they're consistent to the extent that it's applicable.
The license is an important point and it seems that the MIT has always been the correct one as the LICENSE file has it too.

Synchronize the package.json metadata

---

package.json

After some of my changes[1][2] it stopped being possible to import the ts-results-es/rxjs-operators submodule[3].
Cherry-picked from [4] by Jacob Nguyen.
I tested it locally and it worked for me.
[1] 0be48c527e86 ("Make the package ESM-only")
[2] befb3c555552 ("Restore CommonJS compatibility (#5)")
[3] https://github.com/lune-climate/ts-results-es/issues/38
[4] https://github.com/lune-climate/ts-results-es/pull/39

Fix rxjs-operators submodule support

---

package.json

When I did [1] I forgot to remove this tag.
It'd prevent us from publishing the package.
[1] 186af7388ff3 ("Merge the two package.json files (#44)")

Stop claiming this package is private

---

package.json

arethetypeswrong[1] detected two issues in the last release of this package, both when importing the rxjs-operators submodule from CJS code in node16 module resolution mode[2]:
* Masquerading as ESM
* ESM (dynamic import only)
They document this stuff really well. In our case the problam has been we've always been using ESM type declarations regardless of the mode (CJS or ESM).
[3] shows that the "types" declarations can be ommitted if the .cjs/.mjs/.js files have corresponding .d.ts files living in the same directories – which in our case they do:
root@06bb8ded2f98:/lune/ts-results-es# tree dist
dist
|-- cjs
|   |-- index.d.ts
|   |-- index.d.ts.map
|   |-- index.js
|   |-- index.js.map
|   |-- option.d.ts
|   |-- option.d.ts.map
|   |-- option.js
|   |-- option.js.map
|   |-- …

Fix the type declaration files' locations

---

.github/dependabot.yml

This is to keep us up to date with the latest dependency versions.

Set up Dependabot dependency version updates

---

package-lock.json
package.json

Mostly to keep things up to date, but...
I've been experiencing the weirdest test false negatives in my local development environment, namely this wasn't failing:
expect(Ok(1)).toEqual(Ok(123123))
I have no idea why.
The issue is gone after the update.

Update the jest-related packages to the latest versions

---

README.md
src/option.ts
test/option.test.ts

We've done something similar to Ok/Err in [1] so I figured we could change this one too to keep things consistent.
The change is backwards incompatible but in an explicit way – the code using the old name will fail to compile.
We'll document the migration steps for the client code.
[1] c0c3f6c487c1 ("Stop reusing the val property in Ok and Err (#58)")

Rename Some.val to value

---

src/option.ts
src/result.ts

These were either incorrect or inconsistent with the rest of the documentation.

Fix a bunch of docstring typos

---

docs/index.rst
docs/reference/api/index.rst
docs/reference/api/option.rst
docs/reference/api/result.rst
docs/reference/index.rst

This is combination of the docstrings from the code and examples
from the readme with syntax changed from Markdown to reStructuredText.
Once this is merged we can get rid of the related part of the readme
as a Sphinx-based documentation is a superset of it.

Add initial API reference documentation

---

docs/reference/api/asyncresult.rst
docs/reference/api/index.rst
docs/reference/api/result.rst
src/asyncresult.ts
src/index.ts
src/result.ts
test/asyncresult.test.ts
test/result.test.ts

It's very common to see this pattern in our (Lune) code:
const thing: Promise<Result<T, E>> = ...
// Now we want to return an error if Err but if Ok we want to
// process it further with asynchronous code, so first await it:
const result = await thing
// Then manualy branch on the variant:
if (result.isErr()) {
return result
}
// Only now we can process it:
const anotherThing: Promise<Result<U, E>> = asyncFunction(result.value)
// But wait! We want to process it with *another* function
(asyncAnotherFunction).
// That means another await/if/return/process block.
// ...
This PR attempts to make this whole thing much better and now the following will be possible:
return new AsyncResult(thing)
.andThen(asyncFunction)
.andThen(asyncAnotherFunction)
* Why a separate type? Because I didn't find …

Take a first stab at async results

---

CHANGELOG.md
package-lock.json
package.json

We want to experiment with the recently added AsyncResult to see if it meets expectations.
A release explicitly marked as alpha so it's clear things can still change.

Release version 4.1.0-alpha.1

---

src/option.ts
test/option.test.ts

Option.any doesn't actually loop through its arguments, and returns right away.

Fix Option.any behavior

---

package.json

Hello!
Thank you for your fork and active maintenance!
My main motivation for using `ts-results-es` over `ts-results` is compatibility with `esbuild`: after running into the problem noted in [this issue](https://github.com/vultix/ts-results/issues/37) and then reading that discussion, I decided to try to use `ts-results-es`.
However, `ts-results-es` did not work out of the box in my bundling setup. I need to produce a commonjs module (for compatibility with legacy dependencies) from typescript/esm source, but `esbuild --bundle --platform=node --conditions=require` was producing a bundle that imported from `ts-results-es/dist/esm` instead of `ts-results-es/dist/cjs`.
After some digging I determined that the issue is that `esbuild` checks `package.json.exports` in the order that the …

Allow commonjs bundle from esm source

---

.readthedocs.yaml

It seems we've been relying on a Poetry bug (or at least on a buggy behavior)[1].
This made our documentation builds to stop working with Poetry 1.8[2]:
Running Sphinx v7.2.6
making output directory... done
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/ts-results-es/envs/109/lib/python3.11/site-packages/sphinx/cmd/build.py", line 293, in build_main
app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/docs/checkouts/readthedocs.org/user_builds/ts-results-es/envs/109/lib/python3.11/site-packages/sphinx/application.py", line 272, in __init__
self._init_builder()
File "/home/docs/checkouts/readthedocs.org/user_builds/ts-results-es/envs/109/lib/python3.11/site-packages/sphinx/appli …

Fix managing the docs Python virtualenv

---

docs/reference/api/asyncresult.rst
package-lock.json
src/asyncresult.ts
test/asyncresult.test.ts

A follow up to [1].
Two more convenience composition methods in AsyncResults and I was missing recently.
The sync Result has them already (with different signatures, of course).
[1] 3f55d157c925 ("Take a first stab at async results (#87)")

Implement AsyncResult or and orElse

---

docs/pyproject.toml

We use Poetry to manage Python dependencies.
It has a special mode of operation[1] for cases where one doesn't manage their own package (publishing etc.) but only uses Poetry for dependency management – which is exactly our use case.
This allows us to stop providing dummy metadata in pyproject.toml.
[1] https://python-poetry.org/docs/basic-usage/#operating-modes

Configure the documentation dependencies better

---

docs/reference/api/asyncresult.rst

When I added or and orElse I put them in the wrong place (should be ordered alphabetically).

Reorder the AsyncResult methods in the documentation

---

docs/reference/api/asyncresult.rst

I forgot to include it when I pushed [1].
[1] ea052ad51bce ("Implement AsyncResult.mapErr (#113)")

Add a missing mapErr method signature to the documentation

---

docs/reference/api/asyncoption.rst
docs/reference/api/asyncresult.rst
docs/reference/api/index.rst
docs/reference/api/option.rst
src/asyncoption.ts
src/asyncresult.ts
src/index.ts
src/option.ts
test/asyncoption.test.ts
test/asyncresult.test.ts
test/option.test.ts

Something that comes up every now and then and I've been missing it from the ts-results-es API: an asynchronous counterpart to Option.
Also a counterpart to AsyncResult added in [1].
This addition completes the sync/async, Option/Result matrix.
[1] 3f55d157c925 ("Take a first stab at async results (#87)")

Implement AsyncOption

---

CHANGELOG.md
package.json

This PR depends on merging https://github.com/lune-climate/ts-results-es/pull/114 first.
Let's release the changes and start testing them in real applications.

Release version 4.1.0

---

jest.config.js

This PR silences the warnings presented when you run the test suite:
```
> ts-results-es@4.1.0 test
> jest
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
<transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
<transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
...
```

Migrate tsconfig global

---

docs/reference/api/result.rst
src/result.ts
test/result.test.ts

Howdy! I'm bringing this PR over from the decidedly dead vultix/ts-results repo.
This PR adds non-spread variants of `Result.all` and `Result.any` which should be preferred over the parameter spread variants. For instances where `Result.all` or `Result.any` are invoked with very large arrays, [the spread operation could lead to stack overflows](https://github.com/nodejs/node/issues/16870#issuecomment-342773879). 
Additionally, speaking from personal experience in an enterprise environment; the usage of `Result.all` via a spread array (`Result.all(...myResults)`) grossly exceeds the usage of `Result.all` with multiple parameters. I'd imagine this is the same for others as well.
This new behavior has been added as an overload of `Result.all` to offer backwards compatibility for those …

Add non-spread overload for Result.all

---

docs/reference/api/result.rst
src/result.ts
test/result.test.ts

Hello Again! I'm often finding myself adding this tool as a companion utility alongside ts-result, and figured I'd throw it up here to see if it might be accepted as a bundled tool. 
We can sometimes find ourselves in positions where we want to practice error tolerance, that is, proceeding through a function collecting errors as they occur, but continuing with items who've succeeded. I've always been a bit baffled that a library based upon two core items (`Ok` and `Error`), has no bundled utility to separate the two. 
I'm proposing the introduction of `Result.partition(results)` which will return a tuple of `[Ok[], Error[]]` used as 
```typescript
const [oks, errors] = Result.partition(results)
```
A example use case of this would be report generation:
```typescript
function …
```

Add Result.partition feature

---

docs/reference/api/rxjs.md
docs/reference/api/rxjs.rst

The documentation was already wrong in the forked `vultix/ts-results` repo, but that seems deprecated so I'm directing my effort here.

Fix documentation for `filterResultErr()` rxjs operator

---

docs/reference/api/rxjs.rst

This was throwing me off a bit when I first looked at the documentation. The code works as intended, just the comments are a bit off.

Fix misleading comments in documentation example

---

docs/reference/api/option.rst
docs/reference/api/result.rst
src/option.ts
src/result.ts
test/option.test.ts
test/result.test.ts
test/util.ts

Something I re-discovered as missing yesterday, we can definitely use this in some places.
The equivalent of Rust's unwrap_or_else.

Implement {Option,Result}.unwrapOrElse

---

README.md
docs/dev/index.rst
docs/index.rst

Continuing the work started in [1] for easier documentation consumption and maintenance.
[1] 633ccad330e8 ("Set up an initial documentation structure (#81)")

Move the package publishing documentation out of readme

---

README.md
docs/index.rst
docs/tutorials/index.rst
docs/tutorials/option.rst
docs/tutorials/result.rst

Following up the work started in [1].
If we squint a little these examples are tutorial-like, let's put them in the tutorials section.
Following the Diataxis framework[2] for structuring the documentation.
[1] 633ccad330e8 ("Set up an initial documentation structure (#81)")
[2] https://diataxis.fr/

Move the usage examples out of the readme

---

src/result.ts
test/result.test.ts

Hello @jstasiak! I must confess, I hadn't been able to update to the latest version of ts-results-es until recently. I had a shower thought last night that the signature for Result.partition was actually incorrect. 
```Typescript
const all1 = Result.partition([ok0, ok1, err0, err1]);
expect(all1).toEqual([
[ok0.value, ok1.value],
[err0.error, err1.error],
]);
eq<typeof all1, [[number, boolean, never, never], [never, never, symbol, Error]]>(true);
```
The signature above implies that `all` is equal to `[[number, boolean, undefined, undefined], [undefined, undefined, symbol, Error]]` but this is not how that function works. Successes and errors will be pushed onto the partition array as they come, and we can't guarantee what index the successes or errors will be at. The real result from …

Correct signature for Result.partition

---

CHANGELOG.md
src/option.ts
src/result.ts
test/ok.test.ts
test/option.test.ts
test/result.test.ts

Previously iterating Some and Ok objects depended on whether the underlying type T was iterable or not.
If it was the results of the iteration were obtained by iterating the underlying value. There could be an arbitrary number of results.
For example this was the case *before* (using Some to demonstrate the idea, the same applies to Ok):
// Some<number>, no results because 1 is not iterable
for (const e of Some(1)) { ... }
// Some<number[]>, two results produced
for (const e of Some([1, 2])) { ... }
// Some<number[]>, no results produced because the underlying value
// contains no items
for (const e of Some([]) as Option<number[]>) { ... }
This mode of operation never quite worked for me because:
1. It depended on the underlying value being iterable and didn't provide any value in case of …

Change the approach to Option and Result iteration

---

CHANGELOG.md
src/result.ts
test/result.test.ts

The error solved here:
test/result.test.ts:327:38 - error TS2349: This expression is not callable.
Each member of the union type '(<R extends Result<number, unknown>>(_other: (error: never) => R) => OkImpl<number>) | (<R extends Result<unknown, unknown>>(other: (error: string) => R) => R)' has signatures, but none of those signatures are compatible with each other.
327     const resultAfterOrElse = result.orElse((error) => Err(error))
~~~~~~
test/result.test.ts:327:46 - error TS7006: Parameter 'error' implicitly has an 'any' type.
327     const resultAfterOrElse = result.orElse((error) => Err(error))
~~~~~
The same issue existed in both implementations and the fix is basically the same.
There are two aspects of this patch, one I'm pretty confident about and the other remains an open …

Fix not being able to call Result's or and orElse methods

---

test/result.test.ts

This particular test is supposed to verify the handling of array parameters so we need to pass an array (although an empty one).

Fix a non-array Result.any call in the tests

---

CHANGELOG.md
src/asyncresult.ts
test/asyncresult.test.ts

Without these overloads
goodResult.andThen((value) => Promise.resolve(Ok(value * 2)));
was of type
AsyncResult<number, unknown>
which would cause downstream problems.
Granted, this could be an edge case and the map method could be better for this (Ok -> Ok transformation so only the value inside changes) but still, I don't think we should be generating unknown here, hence the patch.
Resolves: https://github.com/lune-climate/ts-results-es/issues/176

Fix the AsyncResult.andThen handling of known-Ok transformations

---

CHANGELOG.md
src/asyncresult.ts
test/asyncresult.test.ts

This patch reverts commit [1] and documents it.
The problem is after [1] the following code
const fromRegularResult = (Ok(1) as Result<number, string>).toAsyncResult();
fromRegularResult.andThen((value) => Ok(value * 2));
would fail co compile:
src/file.ts:169:19 - error TS2349: This expression is not callable.
Each member of the union type '{ <T2>(mapper: (val: never) => Ok<T2> | Promise<Ok<T2>> | AsyncResult<T2, never>): AsyncResult<T2, string>; <T2, E2>(mapper: (val: never) => Result<...> | ... 1 more ... | AsyncResult<...>): AsyncResult<...>; } | { ...; }' has signatures, but none of those signatures are compatible with each other.
169 fromRegularResult.andThen((value) => Ok(value * 2));
~~~~~~~
src/file.ts:169:28 - error TS7006: Parameter 'value' implicitly has an 'any' type.
169 …

Fix an AsyncResult.andThen fix-related regression

---

src/result.ts

There is no need for an implementation signature while declaring overloaded methods in interfaces. It was just redundant.

Remove an unneeded overload from BaseResult.andThen

---

.github/workflows/ci.yml

The 17.x branch is not a Long-Term Support branch and has been unsupported for a long time (last release in 2022[1]).
Let's upgrade to something more modern to make sure the CI process keeps working and the environment is more consistent with what's used to develop this package on our own machines.
Why 22.x instead of 23.x? 22 is an LTS line while the support for 23 will disappear more quickly[1].
Why specific version instead of 22.x? To avoid the exact version changing without our intervention and breaking things.
[1] https://nodejs.org/en/about/previous-releases

Upgrade CI Node from 17.x to 22.14.0

---

docs/reference/asyncoption.rst
src/asyncoption.ts

Results and other Result-adjacent types were used by accident.

Fix some bad references in the AsyncOption docs

---

docs/reference/asyncoption.rst
docs/reference/asyncresult.rst
src/asyncoption.ts
src/asyncresult.ts
test/asyncoption.test.ts
test/asyncresult.test.ts

Just a quality of life feature so we don't have to
await x.promise
but can do
await x
instead when converting from async to sync.

Make Async{Option,Result} thenable/awaitable

---

package-lock.json
src/result.ts
test/err.test.ts
test/ok.test.ts
test/result.test.ts

It's been reported that code like this didn't work:
class T1 { name = "T1" as const }
class T2 { name = "T2" as const }
class T3 { name = "T3" as const }
class T4 { name = "T4" as const }
class T5 { name = "T5" as const }
class T6 { name = "T6" as const }
function foo1(): Result<T1, T2> {
return 0 as any
}
function foo2(): Result<T3, T4> {
return 0 as any
}
function foo3(): Result<T5, T6> {
return 0 as any
}
const a = foo1().andThen(foo2).orElse(foo3) // error
because orElse wasn't callable on the result of the andThen call ("This expression is not callable"):
This expression is not callable.
Each member of the union type '{ <T>(other: (error: T2) => Ok<T>): Result<T, never>; <R extends Result<any, any>>(other: (error: T2) => R): R; } | { <T>(other: (error: T4) => Ok<T>): Result<...>; <R …

Fix Result's andThen and orElse chaining
